// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrDSIbL8ublLQbZ3jjqxDn-oxla-sd2Eo',
    appId: '1:829198589036:web:8101d542f0d8c58b198c49',
    messagingSenderId: '829198589036',
    projectId: 'flower-fire-da6e7',
    authDomain: 'flower-fire-da6e7.firebaseapp.com',
    storageBucket: 'flower-fire-da6e7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4wtnnenv5dQfxw82wnbGUYQ6KmZry4v0',
    appId: '1:829198589036:android:3edb95ceb8f8a0df198c49',
    messagingSenderId: '829198589036',
    projectId: 'flower-fire-da6e7',
    storageBucket: 'flower-fire-da6e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcD7G-R3fHmTSxrSjGf7nuY_p9t__T7Xg',
    appId: '1:829198589036:ios:4279914a23f3c70c198c49',
    messagingSenderId: '829198589036',
    projectId: 'flower-fire-da6e7',
    storageBucket: 'flower-fire-da6e7.appspot.com',
    androidClientId: '829198589036-d69g8p5ldchjkl5ns1m9c6h8n801753l.apps.googleusercontent.com',
    iosClientId: '829198589036-ag52jn0c1g7uecs5so82f66icaur23mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appECommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcD7G-R3fHmTSxrSjGf7nuY_p9t__T7Xg',
    appId: '1:829198589036:ios:4279914a23f3c70c198c49',
    messagingSenderId: '829198589036',
    projectId: 'flower-fire-da6e7',
    storageBucket: 'flower-fire-da6e7.appspot.com',
    androidClientId: '829198589036-d69g8p5ldchjkl5ns1m9c6h8n801753l.apps.googleusercontent.com',
    iosClientId: '829198589036-ag52jn0c1g7uecs5so82f66icaur23mh.apps.googleusercontent.com',
    iosBundleId: 'com.example.appECommerce',
  );

}